-- CATALOG
-- TODO: for portable setup use sqlcmd setvar for file path to de-localize
CREATE DATABASE [XtExport] ON  PRIMARY 
( NAME = N'XtExport', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.ENULL\MSSQL\DATA\XtExport.mdf' , SIZE = 3072KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'XtExport_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.ENULL\MSSQL\DATA\XtExport_log.ldf' , SIZE = 9216KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [XtExport] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [XtExport] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [XtExport] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [XtExport] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [XtExport] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [XtExport] SET ARITHABORT OFF 
GO
ALTER DATABASE [XtExport] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [XtExport] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [XtExport] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [XtExport] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [XtExport] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [XtExport] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [XtExport] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [XtExport] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [XtExport] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [XtExport] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [XtExport] SET  DISABLE_BROKER 
GO
ALTER DATABASE [XtExport] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [XtExport] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [XtExport] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [XtExport] SET  READ_WRITE 
GO
ALTER DATABASE [XtExport] SET RECOVERY FULL 
GO
ALTER DATABASE [XtExport] SET  MULTI_USER 
GO
ALTER DATABASE [XtExport] SET PAGE_VERIFY CHECKSUM  
GO
USE [XtExport]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [XtExport] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO